# Generated by Django 5.0.4 on 2024-06-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllRecords1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kl_no', models.CharField(max_length=100)),
                ('mill_name', models.CharField(max_length=100)),
                ('mill_place', models.CharField(max_length=100)),
                ('mill_rate', models.FloatField()),
                ('mill_weight', models.FloatField()),
                ('mill_remarks', models.TextField(blank=True, null=True)),
                ('mill_total_wages', models.FloatField()),
                ('party_name', models.CharField(max_length=100)),
                ('party_address', models.CharField(max_length=200)),
                ('party_weight', models.FloatField()),
                ('paddy_variety', models.CharField(max_length=100)),
                ('lorry_no', models.CharField(max_length=100)),
                ('lorry_advance', models.FloatField()),
                ('lorry_total_fare', models.FloatField()),
                ('gennius_qty', models.FloatField()),
                ('gennius_price', models.FloatField()),
                ('mill_calculation_type', models.CharField(choices=[('BAGS_X4', 'BAGS X 4'), ('78KGS', '78 KGS'), ('79KGS', '79 KGS'), ('79_Delivery', '79 Delivery'), ('78_Delivery', '78 Delivery'), ('BAGS_X4_Delivery', 'BAGS X 4 Delivery')], max_length=50)),
                ('mill_rate_type', models.CharField(choices=[('party rate', 'party rate'), ('mill rate', 'mill rate')], max_length=100)),
                ('party_calculation_type', models.CharField(choices=[('BAGS_X4', 'BAGS X 4'), ('78KGS', '78 KGS'), ('79KGS', '79 KGS'), ('79_Delivery', '79 Delivery'), ('78_Delivery', '78 Delivery'), ('BAGS_X4_Delivery', 'BAGS X 4 Delivery')], max_length=50)),
                ('party_rate_type', models.CharField(choices=[('mill rate', 'mill rate'), ('party rate', 'party rate')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InterestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('earned_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('party_or_mill', models.CharField(max_length=50)),
                ('ac_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MillsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kl_no', models.CharField(max_length=100)),
                ('mill_name', models.CharField(max_length=100)),
                ('mill_place', models.CharField(max_length=100)),
                ('mill_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mill_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mill_remarks', models.TextField(blank=True)),
                ('mill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mill_calculation_type', models.CharField(choices=[('BAGS_X4', 'BAGS X 4'), ('78KGS', '78 KGS'), ('79KGS', '79 KGS'), ('79_Delivery', '79 Delivery'), ('78_Delivery', '78 Delivery'), ('BAGS_X4_Delivery', 'BAGS X 4 Delivery')], max_length=50)),
                ('mill_rate_type', models.CharField(choices=[('party rate', 'party rate'), ('mill rate', 'mill rate')], max_length=100)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PartyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kl_no', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=100)),
                ('party_address', models.CharField(max_length=200)),
                ('party_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('party_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paddy_variety', models.CharField(max_length=100)),
                ('lorry_no', models.CharField(max_length=50)),
                ('lorry_advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lorry_total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gennius_qty', models.IntegerField()),
                ('party_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gennius_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('party_calculation_type', models.CharField(choices=[('BAGS_X4', 'BAGS X 4'), ('78KGS', '78 KGS'), ('79KGS', '79 KGS'), ('79_Delivery', '79 Delivery'), ('78_Delivery', '78 Delivery'), ('BAGS_X4_Delivery', 'BAGS X 4 Delivery')], max_length=50)),
                ('party_rate_type', models.CharField(choices=[('mill rate', 'mill rate'), ('party rate', 'party rate')], max_length=100)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RecordDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=100)),
                ('party_address', models.CharField(max_length=255)),
                ('mill_name', models.CharField(max_length=100)),
                ('mill_place', models.CharField(max_length=100)),
            ],
        ),
    ]
