# Generated by Django 5.0.4 on 2024-06-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paddymastersystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allrecords1',
            name='gennius_price',
        ),
        migrations.RemoveField(
            model_name='allrecords1',
            name='gennius_qty',
        ),
    ]
