# Generated by Django 5.0.4 on 2024-06-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paddymastersystem', '0003_allrecords_delete_allrecords1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kl_no', models.CharField(max_length=100)),
                ('mill_name', models.CharField(max_length=200)),
                ('party_name', models.CharField(max_length=200)),
                ('mill_amount', models.FloatField()),
                ('party_amount', models.FloatField()),
                ('net_profit_loss', models.FloatField()),
            ],
        ),
    ]
