# Generated by Django 5.0.4 on 2024-06-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paddymastersystem', '0004_transactionrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionRecord',
        ),
    ]
